test: disable cloud-image-validator
CIV is currently failing due to an invalid configuration.  This is
blocking every PR currently.  Until we fix it, let's disable it and
enable when we can.

Ticket for re-enablement: https://issues.redhat.com/browse/HMS-9868

Sample error

  Error: waiting for EC2 Spot Fleet Request (sfr-b6e9637c-8690-44f1-a007-d6f4ee5056d7) fulfillment: unexpected state 'error', wanted target 'fulfilled'. last error: {
    EventInformation: {
      EventDescription: "t3.medium, ami-00b8cf0e30376f680, Linux/UNIX: There is no Spot capacity available that matches your request. ",
      EventSubType: "spotFleetRequestConfigurationInvalid"
    },
    EventType: "error",
    Timestamp: 2025-12-09 14:02:47 +0000 UTC
  }